# Generated by Django 5.0.4 on 2024-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_note_alter_clients_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
